#!/bin/bash

## This script will make a new directory of notes in the present directory

echo "Please enter name of article file directory"

read NAME

echo "Creating file and directory..."

mkdir $NAME && cd $NAME

cp ~/templates/latex/article.tex ./main.tex

echo "Done!"
